
project_id = "kciuuxoqxfsogjuqflou"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.agent-executor]
verify_jwt = true

[functions.knowledge-processor]
verify_jwt = true
