
[build]
  # Install all dependencies including dev dependencies, then build
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  # Set Node.js version for compatibility
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (you'll need to set these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
