global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'supabase'
    static_configs:
      - targets: ['kciuuxoqxfsogjuqflou.supabase.co:443']
    scheme: https
    scrape_interval: 60s