
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kciuuxoqxfsogjuqflou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "<JWT_TOKEN>";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// OAuth and social media helper functions
export const oauthService = {
  async initiateOAuth(platform: string) {
    const { data, error } = await supabase.functions.invoke('oauth-initiate', {
      body: { platform }
    })
    
    if (error) throw error
    return data
  },

  async getConnections() {
    const { data, error } = await supabase.functions.invoke('social-connections', {
      method: 'GET'
    })
    
    if (error) throw error
    return data
  },

  async disconnectPlatform(platform: string) {
    const { data, error } = await supabase.functions.invoke('social-connections', {
      method: 'DELETE',
      body: { platform }
    })
    
    if (error) throw error
    return data
  },

  async postToSocial(platforms: string[], content: any) {
    const { data, error } = await supabase.functions.invoke('social-post', {
      body: { platforms, content }
    })
    
    if (error) throw error
    return data
  }
}
